## Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices,
along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover:
1. The basic of Numpy
2. Focusing on Arrays
3. Vectorized operations

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
# Create array using numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# One dimension array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # This means 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
# Two dimension array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# Numpy Attributes
arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)
print('Shape : \n',arr.shape)
print('Number of Dimension: ',arr.ndim)
print('Size (number of elements): ',arr.size)
print('Data type: ',arr.dtype)
print('Items size (in bytee): ',arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Number of Dimension:  2
Size (number of elements):  6
Data type:  int64
Items size (in bytee):  8


In [6]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print('Addition: ',arr1+arr2)

# Element wise substraction
print('Substraction: ',arr1-arr2)

# Element wise division
print('Division: ',arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [9]:
# Universal Functions
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [11]:
# Array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array: \n',arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr[1][3]

np.int64(8)

In [22]:
#print(arr[1:,2:])
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [30]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [28]:
# Modify Array ELement
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [32]:
arr[1:] = 70
arr

array([[100,   2,   3,   4],
       [ 70,  70,  70,  70],
       [ 70,  70,  70,  70]])

In [35]:
# Statistical concept -- Normalization
#  To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print(f'Normalized data: {normalized_data}')

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print(f'Mean: {mean}')

# Median
median = np.median(data)
print(f'Median: {median}')

# Standard deviation
std_dev = np.std(data)
print(f'Standard deviation: {std_dev}')

# Variance
variance = np.var(data)
print(f'Variance: {variance}')


Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [49]:
# Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data <= 8)]

array([6, 7, 8])